### ISSUE TITLE
ImportError: Import by filename is not supported (in setup instruction)

### ISSUE THREAD

**Issue by josephcjohnsonjr** [openplans/shareabouts#151]
Following Readme.md (https://github.com/openplans/shareabouts/blob/master/doc/README.md) before "Starting and stopping your server" section.

Traceback (most recent call last):
  File "src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Me/Desktop/Development/shareabouts/env/lib/python2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/Me/Desktop/Development/shareabouts/env/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/Users/Me/Desktop/Development/shareabouts/env/lib/python2.7/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Me/Desktop/Development/shareabouts/env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/Me/Desktop/Development/shareabouts/env/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: Import by filename is not supported.

**Comment by BenSturmfels** [comment]
Thanks for the report and sorry it wasn't responded to at the time. Given the age of this issue and that I haven't seen anything similar I'll close this issue.
