### ISSUE TITLE
ImportError: cannot import name patterns

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts#182]
Seems like `patterns` might be deprecated but I'm not sure how to modify src/project/urls.py.

````
$ src/manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x10f7b9848>
Traceback (most recent call last):
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/env/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/frankhebbert/personal/tektonomastics/sa-tektonomastics/shareabouts/src/project/urls.py", line 1, in <module>
    from django.conf.urls import patterns, include, url
ImportError: cannot import name patterns
````

**Comment by fkh** [comment]
Adding `django==1.8` to requirements.txt made the issue go away.

I also manually ran `pip install python-dateutil; pip install ujson`
